/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.siv.vistas;

import com.siv.beans.DetalleVenta;
import com.siv.beans.Movimiento;
import com.siv.beans.Producto;
import com.siv.beans.SessionApp;
import com.siv.services.ProductoSER;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.List;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author willex
 */
public class FrmBusquedaProducto extends javax.swing.JInternalFrame {

    private ProductoSER productoSER;
    DecimalFormatSymbols simbolos = new DecimalFormatSymbols();
    DecimalFormat formateador;
    
    /**
     * Creates new form FrmBusquedaProducto
     */
    public FrmBusquedaProducto() {
        initComponents();
        productoSER = SessionApp.ctx.getBean("productoSER", ProductoSER.class);
        simbolos.setDecimalSeparator('.');
        formateador = new DecimalFormat("####.##",simbolos);
        this.carga_Tabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();

        setBackground(java.awt.Color.blue);
        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setClosable(true);
        setIconifiable(true);

        jPanel1.setBackground(java.awt.Color.darkGray);

        jPanel2.setBackground(new java.awt.Color(137, 172, 219));

        jLabel1.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        jLabel1.setText("BUSQUEDA PRODUCTOS");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "CODIGO", "PRODUCTO", "STOCK"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CODIGO", "PRODUCTO" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/aceptar.png"))); // NOI18N
        jButton3.setMnemonic('S');
        jButton3.setText("Seleccionar");
        jButton3.setToolTipText("");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextField1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        // TODO add your handling code here:
        buscar_en_Filas(this.jTextField1.getText());
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.double_click();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void double_click(){
        int fila = this.jTable1.getSelectedRow();
        Producto c = null;
        try{
            c = productoSER.getProducto(Integer.parseInt(this.jTable1.getValueAt(fila, 0).toString()));
        }catch(Exception e){
            c = null;
        }
        if(c!=null){
            JDesktopPane jdk = this.getDesktopPane();
            JInternalFrame[] lta = jdk.getAllFrames();
            for(JInternalFrame jif : lta){
                if(jif.getClass() == FrmVenta.class){
                    if(!jif.isClosed()){
                        FrmVenta frm = (FrmVenta) jif;
                        if(!this.verificaProducto(frm.ltaDetalles, c)){
                         frm.producto = c;
                         frm.jtProducto.setText(c.getNombre());
                         frm.jtStock.setText(formateador.format(c.getStock()).toString());
                         this.dispose();
                        }
                        else{
                            SessionApp.muestraAdvertencia("Ya existe el producto en la lista");
                        }
                    }
                }
                
                if(jif.getClass() == FrmMtoRegistroProducto.class){
                    if(!jif.isClosed()){
                        FrmMtoRegistroProducto frm = (FrmMtoRegistroProducto) jif;
                         frm.producto_deBusqueda = c;
                         frm.jtNombreProducto.setText(c.getNombre());
                         frm.jtPrecioCompraAc.setText(formateador.format(c.getPrecio_base()).toString());
                         frm.jTUtilidadActual.setText(formateador.format(c.getGanancia()).toString());
                         frm.jtPrecioVentaAC.setText(formateador.format(c.getPrecio_gral()).toString());
                         frm.jTStock.setText(formateador.format(c.getStock()).toString());
                         this.dispose();
                    }
                }
            }
        }else{
            SessionApp.muestraAdvertencia("No se pudo Seleccionar al Objeto");
            return ;
        }
    }
    
    
    private boolean verificaProducto(List<DetalleVenta> lta,Producto p){
        boolean rpta = false;
        if(!lta.isEmpty()){
            for(DetalleVenta x : lta){
                if(x.getProducto().getId()==p.getId()){
                    rpta = true;
                    break;
                }
            }
        }
        return rpta;
    }
    
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount()==2){
            this.double_click();
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void carga_Tabla(){
        String cols[] = {"CODIGO","PRODUCTO","STOCK"};
        List<Producto> lta = null;
        try{
            lta = productoSER.getAll();
        }catch(Exception e){
            SessionApp.muestraError("No se pudo cargar los datos");
            return ;
        }
        Object[][] rows = new Object[lta.size()][cols.length];
        for(int i=0;i<lta.size();i++){
            rows[i][0] = lta.get(i).getId();
            rows[i][1] = lta.get(i).getNombre();
            rows[i][2] = formateador.format(lta.get(i).getStock());
        }
        DefaultTableModel tb = new DefaultTableModel(rows,cols){
            @Override
            public boolean isCellEditable(int row,int col){
                return false;
            }
        };
        jTable1.setModel(tb);
        jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_SUBSEQUENT_COLUMNS);
    }
    
    private void buscar_en_Filas(String buscado){
        carga_Tabla();
        if(!"".equals(buscado)){
            DefaultTableModel tb_ant = (DefaultTableModel) this.jTable1.getModel();
            int j=0,k=0;
            if(this.jComboBox1.getSelectedItem().toString().equalsIgnoreCase("codigo")){
                k=0;
            }
            if(this.jComboBox1.getSelectedItem().toString().equalsIgnoreCase("producto")){
                k=1;
            }
            int LIM = jTable1.getRowCount();
            while(0<LIM){
                if(!tb_ant.getValueAt(j,k).toString().toLowerCase().contains(buscado.toLowerCase())){
                    tb_ant.removeRow(j);
                }
                else{
                    j++;
                }
                LIM--;
            }
            this.jTable1.setModel(tb_ant);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
