/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.siv.vistas;

import com.siv.beans.Logueo;
import com.siv.beans.SessionApp;
import com.siv.beans.Usuario;
import com.siv.services.LogueoSER;
import com.siv.services.UsuarioSER;
import java.awt.event.KeyEvent;
import java.net.InetAddress;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JFrame;

/**
 *
 * @author Administrador
 */
public class FrmLogin extends javax.swing.JFrame {
    
    private UsuarioSER usuarioSER;
    private LogueoSER logueoSER;
    private SimpleDateFormat format;

    /**
     * Creates new form FrmLogin
     */
    public FrmLogin() {
        initComponents();
        usuarioSER = SessionApp.ctx.getBean("usuarioSER",UsuarioSER.class);
        logueoSER = SessionApp.ctx.getBean("logueoSER", LogueoSER.class);
        format = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Abyssinica SIL", 1, 10)); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Usuario:");
        jLabel1.setName(""); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(100, 50));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Clave:");

        jPasswordField1.setNextFocusableComponent(jButton1);
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyPressed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login.png"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        jTextField1.setNextFocusableComponent(jPasswordField1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addComponent(jTextField1))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(this.jPasswordField1.getPassword().length!=0 && !"".equals(this.jTextField1.getText().trim())){
            String pass = new String(this.jPasswordField1.getPassword());
            String usuario = this.jTextField1.getText();
            String id_sistema = SessionApp.os.getId();
            Usuario user = null;
            try{
                user = this.usuarioSER.getUser(usuario, pass, id_sistema);
            }catch(Exception ex){
                SessionApp.muestraError("Error al Loguearse");
                this.jPasswordField1.requestFocus();
            }
            if(user != null){
                SessionApp.user = user;
                Logueo logeo = new Logueo();
                InetAddress h = null;
                String host = "";
                try{
                    h = InetAddress.getLocalHost();
                    host = h.getHostName();
                }catch(Exception ex){
                    host = "error al obtener nombre de host";
                }
                logeo.setUsuario(user);
                logeo.setHost(host);
                logeo.setIp(SessionApp.ip);
                String fi = format.format(new Date());
                logeo.setFecha_inicio(fi);
                logueoSER.insert(logeo);
                SessionApp.fecha_inicio = fi;
                if(user.getTipo().toLowerCase().equals("administrador")){
                    FrmPrincipal frm = new FrmPrincipal();
                    frm.setTitle("Sistema de Inventario y Venta");
                    frm.setLocationRelativeTo(null);
                    frm.setExtendedState(JFrame.MAXIMIZED_BOTH);
                    frm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    frm.setVisible(true);
                }else{
                    FrmPrincipalNoAdmin frm = new FrmPrincipalNoAdmin();
                    frm.setTitle("Sistema de Inventario y Venta");
                    frm.setLocationRelativeTo(null);
                    frm.setExtendedState(JFrame.MAXIMIZED_BOTH);
                    frm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    frm.setVisible(true);
                }
                this.dispose();
            }
        }
        else{
            SessionApp.muestraAdvertencia("usuario y/o Clave en blanco");
            this.jPasswordField1.requestFocus();
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void jPasswordField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            this.jButton1.doClick();
        }
    }//GEN-LAST:event_jPasswordField1KeyPressed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            this.jButton1.doClick();
        }
    }//GEN-LAST:event_jButton1KeyPressed

    private List<Usuario> cargaCombo(){
        List<Usuario> lta = null;
        try{
        lta = usuarioSER.getAll();
        }catch(Exception ex){
            SessionApp.muestraError("Error al cargar Usuarios\nRevise la conexion");
            System.exit(1);
        }
        if(lta != null){
            if(lta.isEmpty()){
                this.jButton1.setEnabled(false);
                SessionApp.muestraError("No existen Usuarios");
            }
        }
        else{
            SessionApp.muestraError("Error al cargar Usuarios");
            System.exit(1);
        }
        return lta;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
