/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.siv.vistas;

import com.siv.beans.OwnerSystem;
import com.siv.beans.SessionApp;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author willex
 */
public class FrmSplash extends javax.swing.JFrame {
    FrmPanelFondo frm_fondo = new FrmPanelFondo();
    
    private OwnerSystem ownerSystem;
    /**
     * Creates new form FrmSplash
     */
    public FrmSplash() {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException e) {}
        this.setUndecorated(true);
        initComponents();
        ownerSystem = SessionApp.ctx.getBean("propietario", OwnerSystem.class);
        iniciar_Carga();
        iniciar_Splash();
        this.setSize(500, 335);
        this.add(frm_fondo, BorderLayout.CENTER);
        this.setLocationRelativeTo(null);
        this.pack();
    }
    
    private void iniciar_Carga() { //Utilizando Hilos
        new Thread() {

            @Override
            public void run() {
                int i = 0;
                while (i <= 100) {
                    i+=2;
                    progreso.setValue(i);
                    try {
                        sleep(100);
                    } catch (Exception e) {
                        
                    }
                }

            }
        }.start();
    }
    
    private void iniciar_Splash() {
        this.getjProgressBar().setBorderPainted(true);
        this.getjProgressBar().setForeground(new Color(100, 120, 50, 50));
        this.getjProgressBar().setStringPainted(true);
    }
    
    public javax.swing.JProgressBar getjProgressBar() {
       return progreso;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        progreso = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 334));

        progreso.setForeground(new java.awt.Color(252, 193, 64));
        progreso.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                progresoStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(progreso, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(226, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(273, Short.MAX_VALUE)
                .addComponent(progreso, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void progresoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_progresoStateChanged
        // TODO add your handling code here:
        if (progreso.getValue()== 100) {
            FrmLogin frm = new FrmLogin();
            frm.setLocationRelativeTo(null);
            frm.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_progresoStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar progreso;
    // End of variables declaration//GEN-END:variables
}
