/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.siv.vistas;

import com.siv.beans.Cliente;
import com.siv.beans.DetalleVenta;
import com.siv.beans.Producto;
import com.siv.beans.SessionApp;
import com.siv.beans.Venta;
import com.siv.services.ProductoSER;
import com.siv.services.VentaSER;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author willex
 */
public class FrmVenta extends javax.swing.JInternalFrame {

    private VentaSER ventaSER;
    private ProductoSER productoSER;
    public Cliente cliente_deBusqueda;
    public List<Producto> ltaProductos;
    public Producto producto;
    public List<DetalleVenta> ltaDetalles;
    private DecimalFormatSymbols simbolos = new DecimalFormatSymbols();
    private DecimalFormat formateador;
    
    /**
     * Creates new form FrmVenta
     */
    public FrmVenta() {
        initComponents();
        this.desactiva_botones(true);
        this.jtNombreCliente.setEditable(false);
        this.jtProducto.setEditable(false);
        this.jtIgv.setEditable(false);
        this.habilitar_cajas(false);
        this.ventaSER = SessionApp.ctx.getBean("ventaSER",VentaSER.class );
        this.productoSER = SessionApp.ctx.getBean("productoSER",ProductoSER.class );
        simbolos.setDecimalSeparator('.');
        formateador = new DecimalFormat("#########.##",simbolos);
    }
    
    private void habilitar_cajas(boolean valor){
        this.jbtnBuscarCliente.setEnabled(valor);
        this.jbtnBuscarProducto.setEnabled(valor);
        this.jtStock.setEditable(valor);
        this.jsCantidad.setEnabled(valor);
        this.jtDescuento.setEditable(valor);
    }
    
    private void desactiva_botones(boolean valor){
        this.jbtnNuevo.setEnabled(valor);
        this.jbtnSalir.setEnabled(true);
        this.jbtnCancelar.setEnabled(!valor);
        this.jbtnGenerar.setEnabled(!valor);
        this.jbtnagregar.setEnabled(!valor);
        this.jbtnquitar.setEnabled(!valor);
        this.jCheckBox1.setEnabled(!valor);
    }
    
    private void limpiar(){
        this.cliente_deBusqueda = null;
        this.jtNombreCliente.setText("");
        this.jtProducto.setText("");
        this.jtDescuento.setText("");
        this.jtSubtotal.setText("");
        this.jtStock.setText("");
        this.jtIgv.setText("");
        this.jtNroVenta.setText("");
        this.jsCantidad.setValue(0);
        this.jtTotal.setText("");
        this.limpiar_filas();
    }
    
    private void limpiar_filas(){
        DefaultTableModel tb = (DefaultTableModel) jTable1.getModel();
        while(tb.getRowCount()>0){
            tb.removeRow(0);
        }
    }
    
    private void genera_nroVenta(){
        String lastNroVenta = this.ventaSER.getLastNroVenta();
        if(!lastNroVenta.equals("")){
            String[] nro_venta_last = lastNroVenta.split("-");
            int nro_sgte = Integer.parseInt(nro_venta_last[0]);
            int ultimoNro = Integer.parseInt(nro_venta_last[1])+1;
            String sgteNroVenta = "";
            String sgteNro = "";
            if(ultimoNro<10){
                sgteNroVenta = "00000"+ultimoNro;
            }
            else if(ultimoNro<100){
                sgteNroVenta = "0000"+ultimoNro;
            }
            else if(ultimoNro<1000){
                sgteNroVenta = "000"+ultimoNro;
            }
            else if(ultimoNro<10000){
                sgteNroVenta = "00"+ultimoNro;
            }
            else if(ultimoNro<100000){
                sgteNroVenta = "0"+ultimoNro;
            }
            else if(ultimoNro<1000000){
                sgteNroVenta = ""+ultimoNro;
            }
            else{
                sgteNro += 1;
            }
            if(nro_sgte<10){
                sgteNro = "000"+nro_sgte;
            }else if(nro_sgte<100){
                sgteNro = "00"+nro_sgte;
            }else if(nro_sgte<1000){
                sgteNro = "0"+nro_sgte;
            }else if(nro_sgte<10000){
                sgteNro = ""+nro_sgte;
            }
            this.jtNroVenta.setText(sgteNro+"-"+sgteNroVenta);
        }else{
            this.jtNroVenta.setText("0001-000001");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jtProducto = new javax.swing.JTextField();
        jbtnBuscarProducto = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtStock = new javax.swing.JTextField();
        jsCantidad = new javax.swing.JSpinner();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        jtDescuento = new javax.swing.JTextField();
        jbtnagregar = new javax.swing.JButton();
        jbtnquitar = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel6 = new javax.swing.JPanel();
        jtSubtotal = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtIgv = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jtTotal = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jbtnGenerar = new javax.swing.JButton();
        jbtnNuevo = new javax.swing.JButton();
        jbtnCancelar = new javax.swing.JButton();
        jbtnSalir = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jbtnBuscarCliente = new javax.swing.JButton();
        jtNombreCliente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jtFecha = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtNroVenta = new javax.swing.JTextField();

        setBackground(java.awt.Color.blue);
        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setClosable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setBackground(java.awt.Color.darkGray);

        jPanel2.setBackground(new java.awt.Color(137, 172, 219));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "GENERAR NUEVA VENTA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16))); // NOI18N

        jPanel4.setBackground(jPanel2.getBackground());

        jLabel7.setText("PRODUCTO :");

        jtProducto.setEditable(false);
        jtProducto.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jbtnBuscarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buscar.png"))); // NOI18N
        jbtnBuscarProducto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnBuscarProducto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnBuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBuscarProductoActionPerformed(evt);
            }
        });

        jLabel8.setText("CANTIDAD :");

        jLabel4.setText("STOCK :");

        jtStock.setEditable(false);
        jtStock.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jsCantidad.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        jsCantidad.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsCantidadStateChanged(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Producto", "Cantidad", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jLabel20.setText("DESCUENTO:");

        jtDescuento.setEditable(false);
        jtDescuento.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtDescuento.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jtDescuentoCaretUpdate(evt);
            }
        });

        jbtnagregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/+.png"))); // NOI18N
        jbtnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnagregarActionPerformed(evt);
            }
        });

        jbtnquitar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/-.png"))); // NOI18N
        jbtnquitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnquitarActionPerformed(evt);
            }
        });

        jCheckBox1.setText("%");
        jCheckBox1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBox1StateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jCheckBox1)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 846, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jsCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnagregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnquitar)
                        .addGap(34, 34, 34))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbtnBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jsCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtnagregar)
                        .addComponent(jbtnquitar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(jPanel2.getBackground());
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jtSubtotal.setEditable(false);
        jtSubtotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtSubtotal.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jtSubtotalCaretUpdate(evt);
            }
        });
        jtSubtotal.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jtSubtotalInputMethodTextChanged(evt);
            }
        });

        jLabel15.setText("SUB. TOTAL:");

        jLabel5.setText("IGV :");

        jtIgv.setEditable(false);
        jtIgv.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtIgv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtIgvActionPerformed(evt);
            }
        });

        jLabel19.setText("TOTAL A PAGAR :");

        jtTotal.setEditable(false);
        jtTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtIgv, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jtIgv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(jtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel7.setBackground(jPanel2.getBackground());
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jbtnGenerar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/guardar.png"))); // NOI18N
        jbtnGenerar.setMnemonic('G');
        jbtnGenerar.setText("GENERAR VENTA");
        jbtnGenerar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnGenerar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGenerarActionPerformed(evt);
            }
        });

        jbtnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nuevo.png"))); // NOI18N
        jbtnNuevo.setMnemonic('N');
        jbtnNuevo.setText("NUEVA");
        jbtnNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNuevoActionPerformed(evt);
            }
        });

        jbtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancelar.png"))); // NOI18N
        jbtnCancelar.setMnemonic('C');
        jbtnCancelar.setText("CANCELAR");
        jbtnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelarActionPerformed(evt);
            }
        });

        jbtnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        jbtnSalir.setMnemonic('S');
        jbtnSalir.setText("SALIR");
        jbtnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(jbtnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnGenerar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBackground(jPanel2.getBackground());
        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel9.setText("CLIENTE :");

        jbtnBuscarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buscar.png"))); // NOI18N
        jbtnBuscarCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnBuscarCliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBuscarClienteActionPerformed(evt);
            }
        });

        jLabel1.setText("FECHA :");

        jtFecha.setEditable(false);
        jtFecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtFecha.setText(new SimpleDateFormat("dd/MM/yyyy").format(new Date()));

        jLabel2.setText("Nro-VENTA :");

        jtNroVenta.setEditable(false);
        jtNroVenta.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtNroVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jtNroVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnBuscarCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jbtnSalirActionPerformed

    private void jbtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelarActionPerformed
        // TODO add your handling code here:
        this.desactiva_botones(true);
        this.limpiar();
        this.ltaProductos = null;
        this.cliente_deBusqueda = null;
    }//GEN-LAST:event_jbtnCancelarActionPerformed

    private void jbtnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNuevoActionPerformed
        // TODO add your handling code here:
        this.desactiva_botones(false);
        this.habilitar_cajas(true);
        this.limpiar();
        this.jtIgv.setText(productoSER.getIGV()+"%");
        this.genera_nroVenta();
        this.jtDescuento.setText("0");
        this.ltaProductos = new ArrayList<Producto>();
        this.ltaDetalles = new ArrayList<DetalleVenta>();
    }//GEN-LAST:event_jbtnNuevoActionPerformed

    private void jbtnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGenerarActionPerformed
        // TODO add your handling code here:
        if(!this.ltaDetalles.isEmpty()){
            if(this.cliente_deBusqueda!=null){
                Venta v = new Venta();
                v.setCliente(cliente_deBusqueda);
                v.setDescuento(Double.parseDouble(this.jtDescuento.getText()));
                v.setFecha(new SimpleDateFormat("yyyy-MM-dd hh:mm:ss").format(new Date()));
                v.setIgv((double)productoSER.getIGV());
                v.setNro_venta(this.jtNroVenta.getText());
                v.setSubtotal(Double.parseDouble(this.jtSubtotal.getText()));
                v.setTotal(Double.parseDouble(this.jtTotal.getText()));
                v.setVendedor(SessionApp.user);
                int rpta = 0;
                rpta = ventaSER.insert(v, ltaDetalles);
                if(rpta == 0){
                    SessionApp.muestraError("Error al Generar la Venta");
                }else{
                    JOptionPane.showMessageDialog(null, "Se genero la venta", "Venta Realizada", JOptionPane.INFORMATION_MESSAGE);
                }
                this.jbtnCancelar.doClick();
                this.jbtnNuevo.doClick();
            }else{
                SessionApp.muestraAdvertencia("Debe escoger un cliente");
            }
        }else{
            SessionApp.muestraAdvertencia("No hay productos en lista");
        }
    }//GEN-LAST:event_jbtnGenerarActionPerformed

    private void jbtnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBuscarClienteActionPerformed
        // TODO add your handling code here:
        FrmBusquedaCliente frm = new FrmBusquedaCliente();
        JDesktopPane jdk = this.getDesktopPane();
        jdk.add(frm);
        frm.moveToFront();
        try{
        frm.setSelected(true);
        }catch(Exception e){}
        frm.setVisible(true);
        frm.show();
    }//GEN-LAST:event_jbtnBuscarClienteActionPerformed

    private void jbtnBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBuscarProductoActionPerformed
        // TODO add your handling code here:
        FrmBusquedaProducto frm = new FrmBusquedaProducto();
        JDesktopPane jdk = this.getDesktopPane();
        jdk.add(frm);
        frm.moveToFront();
        try{
        frm.setSelected(true);
        }catch(Exception e){}
        frm.setVisible(true);
        frm.show();
    }//GEN-LAST:event_jbtnBuscarProductoActionPerformed
    
    private void cargaDetalles(){
        if(this.ltaDetalles!=null){
            String[] cols = {"PRODUCTO","CANTIDAD","TOTAL"};
            Object[][] rows = new Object[this.ltaDetalles.size()][3];
            for(int i=0;i<ltaDetalles.size();i++){
                rows[i][0] = ltaDetalles.get(i).getProducto().getNombre();
                rows[i][1] = ltaDetalles.get(i).getCantidad();
                rows[i][2] = formateador.format(ltaDetalles.get(i).getTotal());
            }
            DefaultTableModel tb = new DefaultTableModel(rows,cols){
                @Override
                public boolean isCellEditable(int r,int f){
                    return false;
                }
            };
            this.jTable1.setModel(tb);
        }
    }
    
    private void jbtnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnagregarActionPerformed
        // TODO add your handling code here:
        if(this.producto!=null){
            if(Integer.parseInt(this.jsCantidad.getValue().toString())!=0){
                DetalleVenta dt = new DetalleVenta();
                dt.setProducto(producto);
                dt.setCantidad(Double.parseDouble(this.jsCantidad.getValue().toString()));
                dt.setTotal(dt.getCantidad()*producto.getPrecio_gral());
                this.ltaDetalles.add(dt);
                this.cargaDetalles();
                this.producto=null;
                this.jtProducto.setText("");
                this.jtStock.setText("");
                this.jsCantidad.setValue(0);
                this.jtSubtotal.setText(formateador.format(this.sumarMontos()).toString());
            }else{
                SessionApp.muestraAdvertencia("Revise la Cantidad del producto");
            }
        }
        else{
            SessionApp.muestraAdvertencia("Seleccione un producto");
        }
    }//GEN-LAST:event_jbtnagregarActionPerformed

    private double sumarMontos(){
        double suma = 0;
        if(this.jTable1.getRowCount()>0){
            DefaultTableModel tb = (DefaultTableModel) this.jTable1.getModel();
            for(int i=0;i<tb.getRowCount();i++){
                double monto = 0;
                try{
                    monto = Double.parseDouble(tb.getValueAt(i, 2).toString());
                }catch(Exception e){
                    monto = 0;
                }
                suma += monto;
            }
        }
        return suma;
    }
    
    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        // TODO add your handling code here:
        JDesktopPane jdk = this.getDesktopPane();
            JInternalFrame[] lta = jdk.getAllFrames();
            for(JInternalFrame jif : lta){
                if(jif.getClass()==FrmBusquedaCliente.class || jif.getClass()==FrmBusquedaProducto.class){
                    if(!jif.isClosed()){
                        jif.dispose();
                    }
                }
            }
    }//GEN-LAST:event_formInternalFrameClosing

    private void jbtnquitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnquitarActionPerformed
        // TODO add your handling code here:
        if(this.jTable1.getRowCount()>0){
            int fila = this.jTable1.getSelectedRow();
            String pp = this.jTable1.getValueAt(fila, 0).toString();
            int idP = this.productoSER.getProductoByNombre(pp).getId();
            DetalleVenta px = null;
            for(DetalleVenta d : this.ltaDetalles){
                if(d.getProducto().getId()==idP){
                    px = d;
                    break;
                }
            }
            if(px != null){
                this.ltaDetalles.remove(px);
            }
            this.cargaDetalles();
            this.jtSubtotal.setText(formateador.format(this.sumarMontos()).toString());
        }else{
            SessionApp.muestraAdvertencia("Selecciona un producto de la lista\npara poder quitarla");
        }
    }//GEN-LAST:event_jbtnquitarActionPerformed

    private void jtSubtotalInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jtSubtotalInputMethodTextChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jtSubtotalInputMethodTextChanged

    private void actualizaTotal(){
        if(!"".equals(this.jtSubtotal.getText())){
            double descuento = 0;
            try{
                descuento = Double.parseDouble(this.jtDescuento.getText());
                if(descuento < 0){
                    //SessionApp.muestraAdvertencia("Error con el descuento...Revise el valor\nSe establecerá valor 0");
                    descuento = 0;
                }
            }catch(Exception e){
                //SessionApp.muestraAdvertencia("Error con el descuento...Revise el valor\nSe establecerá valor 0");
                descuento = 0;
            }
            double st = Double.parseDouble(this.jtSubtotal.getText());
            int igv = this.productoSER.getIGV();
            double monto_igv = st*0.18;
            double totalX = 0;
            totalX = st+monto_igv;
            if(this.jCheckBox1.isSelected()){
                totalX = totalX - (totalX*(descuento/100));
            }
            else{
                totalX = totalX - descuento;
            }
            this.jtTotal.setText(formateador.format(totalX));
        }
    }
    
    private void jtSubtotalCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jtSubtotalCaretUpdate
        // TODO add your handling code here:
        this.actualizaTotal();
    }//GEN-LAST:event_jtSubtotalCaretUpdate

    private void jtDescuentoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jtDescuentoCaretUpdate
        // TODO add your handling code here:
        this.actualizaTotal();
    }//GEN-LAST:event_jtDescuentoCaretUpdate

    private void jCheckBox1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBox1StateChanged
        // TODO add your handling code here:
        this.actualizaTotal();
    }//GEN-LAST:event_jCheckBox1StateChanged

    private void jtIgvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtIgvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtIgvActionPerformed

    private void jsCantidadStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jsCantidadStateChanged
        // TODO add your handling code here:
        Double valor = 0.0;
        try{
        valor = Double.parseDouble(this.jsCantidad.getValue().toString());
        }catch(Exception ex){
            valor = 0.0;
        }
        Double stock = 0.0;
        try{
            stock = Double.parseDouble(this.jtStock.getText());
        }catch(Exception ex){
            stock = 0.0;
        }
        if(valor>stock){
            SessionApp.muestraAdvertencia("No sobrepase el stock");
            this.jsCantidad.setValue(0);
            this.jsCantidad.requestFocus();
        }
    }//GEN-LAST:event_jsCantidadStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnBuscarCliente;
    private javax.swing.JButton jbtnBuscarProducto;
    private javax.swing.JButton jbtnCancelar;
    private javax.swing.JButton jbtnGenerar;
    private javax.swing.JButton jbtnNuevo;
    private javax.swing.JButton jbtnSalir;
    private javax.swing.JButton jbtnagregar;
    private javax.swing.JButton jbtnquitar;
    private javax.swing.JSpinner jsCantidad;
    private javax.swing.JTextField jtDescuento;
    private javax.swing.JTextField jtFecha;
    private javax.swing.JTextField jtIgv;
    public javax.swing.JTextField jtNombreCliente;
    private javax.swing.JTextField jtNroVenta;
    public javax.swing.JTextField jtProducto;
    public javax.swing.JTextField jtStock;
    private javax.swing.JTextField jtSubtotal;
    private javax.swing.JTextField jtTotal;
    // End of variables declaration//GEN-END:variables
}
